[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/message/*"
  to = "/.netlify/functions/get-message-image?id=:splat"
  status = 200
